Update package-version-changed.yml

diff --git a/.github/workflows/package-version-changed.yml b/.github/workflows/package-version-changed.yml
--- a/.github/workflows/package-version-changed.yml
+++ b/.github/workflows/package-version-changed.yml
@@ -1,4 +1,4 @@
-name: Check if npm version has changed (run './upgrade-npm.sh <patch|minor|major>')
+name: Check if npm package version has changed (run 'npm run upgrade-api <patch|minor|major>')
 on:
   workflow_call:
     inputs:
@@ -30,5 +30,5 @@ jobs:
         run: |
           if [ "${{env.MAIN}}" = "${{env.CURRENT}}" ]; then
             echo version did not change main: ${{env.MAIN}}, current: ${{env.CURRENT}};
-            exit 1;
+            echo "::error::Version of ${{ inputs.library-name}} has not been updated" && exit 1;
           fi
